apiVersion: argoproj.io/v1alpha1
kind: Workflow
spec:
  entrypoint: main
  serviceAccountName: argo-server
  templates:
    - name: main
      steps:
        - - name: checkout
            templateRef:
              name: cwft-git-v2
              template: checkout-with-gitops-for-charts
              clusterScope: true
            arguments:
              parameters:
                - name: appName
                  value: '{{workflow.parameters.appName}}'
                - name: branch
                  value: '{{workflow.parameters.branch}}'
                - name: gitUrlNoProtocol
                  value: '{{workflow.parameters.gitUrlNoProtocol}}'

        - - name: get-macro-chart-version
            templateRef:
              name: cwft-helm-v2
              template: get-macro-chart-version-from-gitops-repo
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: '{{steps.checkout.outputs.artifacts.repo-source}}'
              parameters:
                - name: gitopsSourceFile
                  value: '{{workflow.parameters.gitopsSourceFile}}'

        - - name: get-release-version-from-rc
            templateRef:
              name: cwft-helm-v2
              template: get-release-version-from-rc
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: '{{steps.checkout.outputs.artifacts.repo-source}}'
              parameters:
                - name: rcVersion
                  value: '{{steps.get-macro-chart-version.outputs.result}}'


        - - name: set-macro-chart-version-kubefirst-pro
            templateRef:
              name: cwft-helm-v2
              template: set-macro-chart-version
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: '{{steps.checkout.outputs.artifacts.repo-source}}'
              parameters:
                - name: chartDir
                  value: 'charts/kubefirst-pro'
                - name: chartVersion
                  value: '{{steps.get-release-version-from-rc.outputs.result}}'

        - - name: set-kubefirst-version-in-values-yaml-kubefirst-pro
            templateRef:
              name: cwft-helm-v2
              template: set-kubefirst-version-in-values-yaml
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: '{{steps.set-macro-chart-version-kubefirst-pro.outputs.artifacts.repo-source}}'
              parameters:
                - name: appName
                  value: '{{workflow.parameters.appName}}'
                - name: chartDir
                  value: 'charts/kubefirst-pro'
                - name: chartVersion
                  value: '{{steps.get-release-version-from-rc.outputs.result}}'

        - - name: set-macro-chart-version
            templateRef:
              name: cwft-helm-v2
              template: set-macro-chart-version
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: '{{steps.set-kubefirst-version-in-values-yaml-kubefirst-pro.outputs.artifacts.repo-source}}'
              parameters:
                - name: chartDir
                  value: 'charts/kubefirst'
                - name: chartVersion
                  value: '{{steps.get-release-version-from-rc.outputs.result}}'

        - - name: set-kubefirst-version-in-values-yaml
            templateRef:
              name: cwft-helm-v2
              template: set-kubefirst-version-in-values-yaml
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: '{{steps.set-macro-chart-version.outputs.artifacts.repo-source}}'
              parameters:
                - name: appName
                  value: '{{workflow.parameters.appName}}'
                - name: chartDir
                  value: 'charts/kubefirst'
                - name: chartVersion
                  value: '{{steps.get-release-version-from-rc.outputs.result}}'

        - - name: commit-release-chart-increment
            templateRef:
              name: cwft-git-v2
              template: pull-commit-sign-push
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: '{{steps.set-kubefirst-version-in-values-yaml.outputs.artifacts.repo-source}}'
                  # from: '{{steps.set-macro-chart-version.outputs.artifacts.repo-source}}'
              parameters:
                - name: repoName
                  value: 'charts'
                - name: gitUrlNoProtocol
                  value: '{{workflow.parameters.gitUrlNoProtocol}}'
                - name: commitMessage
                  # Please, be careful updating this message, it must comply with:
                  # github skip ci rule: https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/
                  # github skip ci rule: https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs
                  # gitlab skip ci rule: https://devops.stackexchange.com/questions/6809/is-there-a-ci-skip-option-in-gitlab-ci
                  # in case, the rule is disbaled or don't work this step will create a circular trigger of builds and bumps of version.
                  value: "[skip ci] [CI SKIP] setting kubefirst chart to release version {{steps.get-release-version-from-rc.outputs.result}}\n\nskip-checks:true"

        # Kubefirst OSS
        - - name: publish-helm-chart
            templateRef:
              name: cwft-helm-v2
              template: publish-chart
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: '{{steps.commit-release-chart-increment.outputs.artifacts.repo-source}}'
              parameters:
                - name: appName
                  value: 'charts'
                - name: chartDir
                  value: 'charts/kubefirst'

        # Kubefirst Pro
        - - name: publish-helm-chart-kubefirst-pro
            templateRef:
              name: cwft-helm-v2
              template: publish-chart
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: '{{steps.commit-release-chart-increment.outputs.artifacts.repo-source}}'
              parameters:
                - name: appName
                  value: 'charts'
                - name: chartDir
                  value: 'charts/kubefirst-pro'

        - - name: release-and-tag-main-with-notes
            templateRef:
              name: cwft-git-v2
              template: release-and-tag-main-with-notes
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: '{{steps.commit-release-chart-increment.outputs.artifacts.repo-source}}'
              parameters:
                - name: orgName
                  value: 'konstructio'
                - name: appName
                  value: 'charts'
                - name: tagName
                  value: 'kubefirst-v{{steps.get-release-version-from-rc.outputs.result}}'

        - - name: pull-sign-commit-push-gitops-template
            templateRef:
              name: cwft-git-v2
              template: pull-sign-commit-push-gitops-template
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: '{{steps.checkout.outputs.artifacts.repo-source}}'
              parameters:
                - name: appName
                  value: 'gitops-template'
                - name: commitMessage
                  value: 'set released macro chart for kubefirst - {{steps.get-release-version-from-rc.outputs.result}}'
                - name: nextChartVersion
                  value: '{{steps.get-release-version-from-rc.outputs.result}}'

        - - name: pull-sign-commit-push-kubefirst
            templateRef:
              name: cwft-git-v2
              template: pull-sign-commit-push-kubefirst
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: '{{steps.checkout.outputs.artifacts.repo-source}}'
              parameters:
                - name: appName
                  value: 'kubefirst'
                - name: commitMessage
                  value: 'set next macro chart for kubefirst - {{steps.get-release-version-from-rc.outputs.result}}'
                - name: chartVersion
                  value: '{{steps.get-release-version-from-rc.outputs.result}}'
                - name: environment
                  value: "unused"

        - - name: set-environment-version-for-macro-chart
            templateRef:
              name: cwft-helm-v2
              template: set-environment-version-for-macro-chart
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: '{{steps.checkout.outputs.artifacts.repo-source}}'
              parameters:
                - name: fullChartPath
                  value: '{{workflow.parameters.gitopsDestinationFile}}'
                - name: chartVersion
                  value: '{{steps.get-release-version-from-rc.outputs.result}}'
                - name: environment
                  value: '{{workflow.parameters.environment}}'

        - - name: commit
            templateRef:
              name: cwft-git-v2
              template: pull-commit-sign-push
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: '{{steps.set-environment-version-for-macro-chart.outputs.artifacts.repo-source}}'
              parameters:
                - name: repoName
                  value: 'gitops'
                - name: gitUrlNoProtocol
                  value: '{{workflow.parameters.gitUrlNoProtocol}}'
                - name: commitMessage
                  value: 'setting kubefirst {{workflow.parameters.environment}} to chart version {{steps.get-release-version-from-rc.outputs.result}}'

